name: CMake

on:
  push:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        name: [clang, gcc]
        os: [ubuntu-latest]
        include:
          - name: clang
            cc: clang-8
            cxx: clang++-8

          - name: gcc
            cc: gcc-9
            cxx: g++-9
    steps:
      - uses: actions/checkout@v2
      - name: Setup the container.
        run: docker pull nashtrash/isd-base
      - name: Start the container.
        run: docker run -itd -e CC=${{ matrix.cc }} -e CXX=${{ matrix.cxx }} --name build nashtrash/isd-base
      - name: Copy repo and deps over.
        run: docker cp . build:/repo
      - name: Configure.
        run: docker exec -t build cmake -H/repo -B/build
      - name: Build.
        run: docker exec -t build cmake --build /build
      - name: Run.
        run: docker exec -t build bash -c "cd /repo/bin && ./testing"
      
